- .eslintrc
- docs/examples/checkbox/group.vue
- package.json
- packages/button/button_drip.vue
> fix: solve lint warning

- docs/examples/input/basic.vue
- docs/examples/input/clearable.vue
- docs/examples/input/disabled.vue
- docs/examples/input/label.vue
- docs/examples/input/size.vue
- docs/zh-cn/components/input.md
- package-lock.json
- package.json
- packages/index.js
- packages/input/index.js
- packages/input/input.vue
> feat(input): add component and examples

- docs/examples/footnote/basic.vue
- docs/examples/footnote/target.vue
- docs/zh-cn/components/footnote.md
- packages/footnote/footnote.vue
- packages/footnote/index.js
- packages/index.js
> feat(footnote): add component footnote

- README.md
- public/index.html
> docs(readme): add logo

- docs/examples/footnote/target.vue
- docs/examples/select/basic.vue
- docs/examples/select/disabled.vue
- docs/examples/select/simple.vue
- docs/examples/select/size.vue
- docs/zh-cn/components/select.md
- package-lock.json
- package.json
- packages/index.js
- packages/input/input.vue
- packages/select/index.js
- packages/select/select.vue
- packages/select/select_option.vue
> feat(select): add component and examples

- docs/examples/more/basic.vue
- docs/examples/more/default.vue
- docs/examples/more/loading.vue
- docs/zh-cn/components/more.md
- package-lock.json
- package.json
- packages/index.js
- packages/more/index.js
- packages/more/more.vue
> feat(more): add component and examples

- .github/auto_assign.yml
- now.json
> ci(auto_assign): auto assign when review approve

- docs/examples/toggle/basic.vue
- docs/examples/toggle/disabled.vue
- docs/zh-cn/components/toggle.md
- packages/index.js
- packages/toggle/index.js
- packages/toggle/toggle.vue
> feat(toggle): add component and examples

- docs/examples/fieldset/custom.vue
- docs/examples/fieldset/disabled.vue
- package-lock.json
- package.json
> chore: migrate to vue 2.6

- docs/examples/rate/basic.vue
- docs/examples/rate/disabled.vue
- docs/zh-cn/components/rate.md
- package-lock.json
- package.json
- packages/index.js
- packages/rate/index.js
- packages/rate/rate.vue
> feat(rate): add component and examples

- src/components/doc.vue
> fix: fix doc module match

- docs/examples/tag/basic.vue
- docs/zh-cn/components/tag.md
- packages/index.js
- packages/tag/index.js
- packages/tag/tag.vue
> feat(tag): component and example

- docs/examples/tag/basic.vue
> fix(tag example): fix style

- docs/examples/button/ghost.vue
- docs/examples/toast/action.vue
- docs/examples/toast/basic.vue
- docs/examples/toast/duration.vue
- docs/examples/toast/handler.vue
- docs/examples/toast/status.vue
- docs/zh-cn/components/button.md
- docs/zh-cn/components/toast.md
- package-lock.json
- package.json
- packages/button/button.vue
- packages/button/button_drip.vue
- packages/index.js
- packages/toast/index.js
- packages/toast/service.js
- packages/toast/toast.vue
- packages/utils/bounding.js
> feat(toast): add component and examples

- docs/examples/note/basic.vue
- docs/examples/note/type.vue
- docs/examples/tag/basic.vue
- docs/zh-cn/components/note.md
- docs/zh-cn/components/tag.md
- package-lock.json
- packages/index.js
- packages/note/index.js
- packages/note/note.vue
- packages/tag/tag.vue
> feat(note): component and examples

- docs/examples/spinner/basic.vue
- docs/examples/spinner/size.vue
- docs/zh-cn/components/spinner.md
- package-lock.json
- package.json
- packages/index.js
- packages/spinner/index.js
- packages/spinner/spinner.vue
> feat(spinner): add component and examples

- docs/examples/footnote/basic.vue
- docs/examples/footnote/cursor.vue
- docs/examples/footnote/help.vue
- docs/zh-cn/components/footnote.md
- packages/footnote/footnote.vue
> feat(footnote): add cursor option & example & fix example space

- .circleci/config.yml
- .travis.yml
- docs/examples/popover/align.vue
- docs/examples/popover/basic.vue
- docs/examples/popover/command.vue
- docs/examples/popover/split.vue
- docs/zh-cn/components/popover.md
- package.json
- packages/index.js
- packages/popover/index.js
- packages/popover/popover.vue
- packages/popover/popover_item.vue
- yarn.lock
> feat: popover component

- README.md
- docs/zh-cn/start/installation.md
> docs: update import guide for style

- docs/examples/avatar/size.vue
- package.json
- packages/avatar/avatar.vue
> fix: add medium to size prop

- docs/examples/radio/basic.vue
- docs/examples/radio/disabled.vue
- docs/examples/radio/group.vue
- docs/zh-cn/components/radio.md
- package.json
- packages/avatar/avatar.vue
- packages/index.js
- packages/radio/index.js
- packages/radio/radio.vue
- packages/radio/radio_group.vue
- packages/toast/service.js
> fix(radio): add radio component and doc

- docs/examples/link/basic.vue
- docs/examples/link/more.vue
- docs/examples/link/style.vue
- docs/examples/link/to.vue
- docs/zh-cn/components/link.md
- package.json
- packages/index.js
- packages/link/index.js
- packages/link/link.vue
> feat(link): init component and examples

- README.md
- docs/zh-cn/start/installation.md
- package.json
- packages/index.js
- packages/link/link.vue
- packages/style.css
- src/main.js
> docs: update docs about style

- docs/examples/switcher/basic.vue
- docs/examples/switcher/multiple.vue
- packages/switcher/switcher.vue
> fix(switcher): fix props validate & adjust example

- docs/examples/dialog/baisc.vue
- docs/examples/dialog/custom.vue
- docs/examples/dialog/more.vue
- docs/zh-cn/components/dialog.md
- package.json
- packages/dialog/dialog.styl
- packages/dialog/dialog.vue
- packages/dialog/index.js
- packages/index.js
> feat(dialog): init component and examples

- docs/examples/button/type.vue
- docs/examples/switcher/basic.vue
- docs/examples/switcher/multiple.vue
- package.json
- packages/switcher/switcher.vue
- yarn.lock
> chore: release v0.4.2

- package.json
- packages/code/code.vue
- packages/popover/popover.styl
- packages/popover/popover.vue
- packages/popover/popover_item.vue
- yarn.lock
> fix(code): remove unused code

- docs/examples/progress/basic.vue
- docs/examples/progress/color.vue
- docs/examples/progress/fixed.vue
- docs/zh-cn/components/progress.md
- package.json
- packages/index.js
- packages/progress/index.js
- packages/progress/progress.vue
- yarn.lock
> feat(progress): add progress component

- package.json
- packages/link/link.vue
> fix(link): solve icon misalignment

- docs/examples/table/basic.vue
- docs/zh-cn/components/badge.md
- docs/zh-cn/components/files.md
- docs/zh-cn/components/footnote.md
- docs/zh-cn/components/popover.md
- docs/zh-cn/components/select.md
- docs/zh-cn/components/spinner.md
- docs/zh-cn/components/switcher.md
- docs/zh-cn/components/toast.md
- docs/zh-cn/components/toggle.md
- packages/table/table-body.js
- packages/table/table.styl
- packages/table/table.vue
> fix(table): revise hover color

- docs/en-us/components/files.md
- docs/en-us/components/footnote.md
- docs/en-us/components/input.md
- docs/en-us/components/link.md
- docs/examples/link/basic.vue
> fix(docs): add files footnote input link docs

- docs/examples/toast/handler.vue
Some typo in the toast example
> fix: Typo inside handler.vue

- docs/en-us/components/more.md
- docs/en-us/components/note.md
- docs/en-us/components/popover.md
- docs/en-us/components/progress.md
- docs/en-us/components/radio.md
- docs/en-us/components/rate.md
- docs/en-us/components/select.md
- docs/en-us/components/spinner.md
- docs/en-us/components/switcher.md
- docs/en-us/components/tag.md
- docs/en-us/components/toast.md
- docs/en-us/components/toggle.md
> docs: improve attribute docs

- README.md
> docs: append showcase

- docs/en-us/components/checkbox.md
- docs/en-us/components/popover.md
- docs/en-us/components/table.md
- docs/en-us/components/toggle.md
- docs/examples/table/basic.vue
- packages/progress/progress.vue
- packages/table/table-body.js
- packages/table/table-column.js
- packages/table/table-store.js
> docs: add attribute docs

- docs/examples/table/basic.vue
- packages/table/table.styl
- packages/table/table.vue
> fix(table): table style problem

- package.json
- yarn.lock
> chore: release 0.6.0

- packages/link/link.vue
- packages/toast/service.js
> fix: remove unused

- docs/en-us/start/installation.md
- examples/umd/index.html
- packages/index.js
> fix: fix install on UMD mode

- docs/en-us/components/switcher.md
- docs/examples/switcher/basic.vue
- docs/examples/switcher/multiple.vue
- package.json
- packages/switcher/index.js
- packages/switcher/switcher-item.vue
- packages/switcher/switcher.vue
> feat(switcher): upgrade interfaces

- src/main.js
> fix(main): fix typo

- packages/input/input.vue
> fix(input): fix clearicon missing in dark mode

- packages/popover/popover-icon.vue
- packages/popover/popover-item.vue
- packages/popover/popover.styl
- packages/popover/popover.vue
> fix: fix popover

- packages/files/files-status.vue
> fix(files): fix color of the status icon

- README.md
> docs: add nut showcase

- packages/link/link.styl
- packages/link/link.vue
- packages/progress/progress.styl
- packages/slider/slider.vue
- packages/table/table.vue
> fix: optimize link style & add slider touch event

- docs/examples/slider/basic.vue
- docs/examples/slider/step.vue
- packages/slider/slider.styl
- packages/slider/slider.vue
> fix(slider): add railWidth listner

- packages/popover/popover-icon.vue
- packages/popover/popover.vue
> fix(popover): update theme when popover triggered

- docs/en-us/start/theme.md
> docs: update theme

- docs/en-us/components/radio.md
- docs/examples/radio/basic.vue
- docs/examples/radio/disabled.vue
- docs/examples/radio/group.vue
- packages/radio/radio.styl
- packages/radio/radio.vue
> fix(radio): modify radio style

- docs/en-us/components/layout.md
- docs/examples/layout/alignment.vue
- docs/examples/layout/basic.vue
- docs/examples/layout/column.vue
- docs/examples/layout/compose.vue
- docs/examples/layout/spacing.vue
- packages/col/col.styl
- packages/col/col.vue
- packages/col/index.js
- packages/index.js
- packages/row/index.js
- packages/row/row.vue
- src/components/examples/footer.vue
> feat: add layout component

- docs/en-us/components/slider.md
- docs/examples/radio/group.vue
- docs/examples/slider/basic.vue
- docs/examples/slider/disabled.vue
- docs/examples/slider/range.vue
- docs/examples/slider/step.vue
- packages/radio/radio.styl
- packages/slider/slider.styl
- packages/slider/slider.vue
> fix(slider): add disabled & slider's range

- docs/en-us/components/note.md
- docs/examples/note/basic.vue
- docs/examples/note/filled.vue
- docs/examples/note/type.vue
- docs/examples/slider/range.vue
- packages/note/note.styl
- packages/note/note.vue
> fix(note): modify note

- docs/en-us/components/tooltip.md
- docs/examples/tooltip/basic.vue
- docs/examples/tooltip/clickable.vue
- docs/examples/tooltip/components.vue
- docs/examples/tooltip/custom.vue
- docs/examples/tooltip/delay.vue
- package.json
- packages/index.js
- packages/tooltip/index.js
- packages/tooltip/tooltip.styl
- packages/tooltip/tooltip.vue
- yarn.lock
> feat(tooltip): add component

- docs/en-us/components/link.md
- docs/en-us/start/installation.md
- docs/examples/link/basic.vue
- docs/examples/link/more.vue
- docs/examples/link/to.vue
- packages/link/link-icon.vue
- packages/link/link.styl
- packages/link/link.vue
- packages/switcher/switcher.styl
> fix(switcher): fix style on actived

- packages/toast/toast.styl
Fix the correct animation reference in toast.
> fix(toast): animation reference

- docs/en-us/start/installation.md
> docs: add missing import statement

- docs/en-us/components/popover.md
- docs/examples/popover/hoverable.vue
- packages/popover/popover.vue
> feat(popover): add hoverable type

- docs/en-us/components/description.md
- docs/examples/description/default.vue
- docs/examples/description/slot.vue
- packages/description/description.styl
- packages/description/description.vue
- packages/description/index.js
- packages/index.js
> feat(description): add description component

- yarn.lock
> chore(deps): bump deps for security alerts

- .circleci/config.yml
- .github/workflows/publish.yml
- package.json
- yarn.lock
> ci: add GH Actions for publish

- packages/utils/theme.js
style: optimize the style of code in themes
fixed #118
> fix(ssr): fix err in theme functions without Document

- docs/en-us/components/textarea.md
- docs/examples/table/delete.vue
- docs/examples/textarea/basic.vue
- docs/examples/textarea/disabled.vue
- docs/examples/textarea/type.vue
- packages/index.js
- packages/textarea/index.js
- packages/textarea/textarea.styl
- packages/textarea/textarea.vue
> feat(textarea): add textarea component

- README.md
> chore: remove outdated case

- packages/avatar/avatar.vue
- packages/card/card.vue
- packages/col/col.vue
- packages/row/row.vue
> fix: card&layout&avatar add $listeners

- docs/examples/link/basic.vue
- package.json
- packages/link/link-icon.vue
- packages/link/link.styl
- packages/link/link.vue
- yarn.lock
> feat(link): improve component to follow new design

- docs/en-us/components/note.md
- packages/note/note.styl
- packages/note/note.vue
> feat(note): improve component to follow new design

- docs/en-us/components/input.md
- docs/examples/input/type.vue
- packages/input/input.styl
- packages/input/input.vue
> fix: add input type & event

- docs/en-us/components/input.md
- docs/examples/input/icon.vue
- package.json
- packages/input/input.styl
- packages/input/input.vue
- src/components/examples/code.vue
- yarn.lock
> feat(input): support for external icons

- packages/toggle/toggle.styl
> fix(toggle): upgrade style

- docs/en-us/components/image.md
- docs/en-us/start/installation.md
- docs/en-us/start/theme.md
- docs/examples/image/shadow.vue
- packages/image/image.vue
> feat(image): add shadow style

- docs/en-us/components/dot.md
- docs/examples/dot/basic.vue
- docs/examples/dot/label.vue
- packages/dot/dot.styl
- packages/dot/dot.vue
- packages/dot/index.js
- packages/index.js
> feat(dot): add component & style

- docs/en-us/components/spacer.md
- docs/examples/spacer/horizontal.vue
- docs/examples/spacer/vertical.vue
- packages/index.js
- packages/spacer/index.js
- packages/spacer/spacer.styl
- packages/spacer/spacer.vue
> feat(spacer): add component & style

- src/app.vue
- src/router.js
> docs: fix multiple routes error on page reload

- docs/en-us/components/spacer.md
- docs/en-us/components/tag.md
- docs/examples/spacer/horizontal.vue
- docs/examples/spacer/vertical.vue
- docs/examples/tag/basic.vue
- docs/examples/tag/type.vue
- docs/zh-cn/components/spacer.md
- docs/zh-cn/components/tag.md
- packages/spacer/spacer.vue
- packages/tag/tag.styl
> fix: update tag's styles & spacer check type

- docs/zh-cn/components/badge.md
> docs(badge): fix typo

- docs/en-us/components/note.md
- docs/examples/note/filled.vue
- docs/examples/note/type.vue
- docs/zh-cn/components/note.md
- packages/note/note.styl
- packages/note/note.vue
> fix(note): fix inaccurate naming on props

- packages/dialog/dialog.vue
> fix(dialog): fix external model is ignored when component mounted

- docs/en-us/components/tabs.md
- docs/examples/switcher/multiple.vue
- docs/examples/tabs/basic.vue
- docs/examples/tabs/disabled.vue
- docs/examples/tabs/icon.vue
- docs/zh-cn/components/tabs.md
- packages/index.js
- packages/tabs/index.js
- packages/tabs/tabs-item.vue
- packages/tabs/tabs.styl
- packages/tabs/tabs.vue
> feat(tabs): add component

- docs/en-us/components/tabs.md
- docs/zh-cn/components/tabs.md
- packages/tabs/tabs.styl
> fix(tabs): fix styles of mouse pointer

- packages/button/button.vue
Fix the button component computed `classes` invoke trim
> fix: the button component computed `classes` invoke trim

- src/components/examples/code-render.vue
- src/components/examples/footer.vue
- src/pages/documents/document-slot.vue
> Fix docs styles

- packages/button/button.vue
> Remove uesless code

- package.json
- packages/code/code.styl
- packages/fieldset/fieldset.styl
- src/pages/documents/document-slot.vue
- yarn.lock
> fix: improve spacing of multiple components

- packages/input/input.vue
Sometimes the setTimeout dose not well work
> Fix the input component

- packages/toast/service.js
- packages/toast/toast.styl
remove css animation, only use transform & add hover interactive
> Fix the toast

- src/app.vue
- src/components/blocks/side.styl
> docs: improve scrollbar on windows

- docs/zh-cn/customization/colors.md
提现--->体现
Fix Chinese translation.
> docs: fix Chinese translation

- docs/en-us/components/collapse.md
- docs/examples/collapse/shadow.vue
- docs/examples/collapse/subtitle.vue
- docs/zh-cn/components/collapse.md
- packages/collapse/collapse-item.vue
- packages/collapse/collapse.styl
- packages/progress/progress.vue
> fix(collapse): add model & update style

- docs/en-us/getting-started/installation.md
- docs/en-us/getting-started/introduction.md
- package.json
- packages/card/card.styl
- yarn.lock
> feat: improve Card and docs

- docs/en-us/components/display.md
- docs/en-us/components/user.md
- docs/examples/user/basic.vue
- docs/examples/user/description.vue
- docs/examples/user/social.vue
- docs/zh-cn/components/display.md
- docs/zh-cn/components/user.md
- packages/avatar/avatar.vue
- packages/display/display.styl
- packages/index.js
- packages/user/index.js
- packages/user/user.styl
- packages/user/user.vue
> feat(user): add component & doc

- docs/en-us/components/grid.md
- docs/examples/grid/auto-width.vue
- docs/examples/grid/basic.vue
- docs/examples/grid/fluid.vue
- docs/examples/grid/responsive.vue
- docs/zh-cn/components/files.md
- docs/zh-cn/components/grid.md
- packages/grid/flex-passthrough.js
- packages/grid/grid.vue
- packages/grid/index.js
- packages/index.js
> feat(grid): add component & doc

- src/components/blocks/side.styl
- src/components/blocks/side.vue
> docs: fix touch event on firefox

- package.json
- packages/tooltip/tooltip.styl
- packages/tooltip/tooltip.vue
- yarn.lock
> feat(tooltip): upgrade popover to v2

- docs/examples/button/basic.vue
- packages/button/button.styl
- packages/button/button.vue
> fix(button): add style for tab selected & update style bug

- packages/dialog/dialog.vue
- packages/fieldset/fieldset.styl
- packages/utils/bodyScroll.js
- packages/utils/index.js
> feat: add bodyScroll function

- docs/examples/snippet/basic.vue
- packages/dialog/dialog.styl
- packages/select/down-icon.vue
- packages/utils/bodyScroll.js
- packages/utils/validator.js
- src/app.vue
- src/components/examples/arrow-icon.vue
> fix(dialog): fix the problem about scrollbar

- docs/en-us/components/grid.md
- docs/examples/grid/hidden.vue
- docs/zh-cn/components/grid.md
- packages/grid/grid.vue
- src/components/blocks/side.vue
> feat(grid): add function of hide grid item

- package.json
- src/components/blocks/side.styl
- src/components/examples/code.vue
- src/main.js
- yarn.lock
> chore: delete vue-clipboard2

- docs/en-us/getting-started/installation.md
- docs/examples/button/custom-icon.vue
- docs/examples/button/icon.vue
- docs/zh-cn/getting-started/installation.md
- packages/code/code.styl
- packages/code/code.vue
- packages/toast/service.js
- packages/toast/toast.styl
> fix: fix toast & code's style & installation doc
